config/routes.rb
Map::Application.routes.draw do
  resources :unidadevangelismos

  resources :grupo_biblicos

  resources :congregacions
  
  match 'vermapa' => 'congregacions#vermapa' 
  

  root :to => 'congregacions#index'

end

app/models/congregacion.rb
class Congregacion < ActiveRecord::Base
end

app/models/grupo_biblico.rb
class GrupoBiblico < ActiveRecord::Base
end

app/models/unidadevangelismo.rb
class Unidadevangelismo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/congregacions_controller.rb
class CongregacionsController < ApplicationController
  # GET /congregacions
  # GET /congregacions.json
  def index
    @congregacions = Congregacion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @congregacions }
    end
  end

  # GET /congregacions/1
  # GET /congregacions/1.json
  def show
    @congregacion = Congregacion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @congregacion }
    end
  end

  # GET /congregacions/new
  # GET /congregacions/new.json
  def new
    @congregacion = Congregacion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @congregacion }
    end
  end

  # GET /congregacions/1/edit
  def edit
    @congregacion = Congregacion.find(params[:id])
  end

  # POST /congregacions
  # POST /congregacions.json
  def create
    @congregacion = Congregacion.new(params[:congregacion])

    respond_to do |format|
      if @congregacion.save
        format.html { redirect_to @congregacion, notice: 'Congregacion was successfully created.' }
        format.json { render json: @congregacion, status: :created, location: @congregacion }
      else
        format.html { render action: "new" }
        format.json { render json: @congregacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /congregacions/1
  # PUT /congregacions/1.json
  def update
    @congregacion = Congregacion.find(params[:id])

    respond_to do |format|
      if @congregacion.update_attributes(params[:congregacion])
        format.html { redirect_to @congregacion, notice: 'Congregacion was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @congregacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /congregacions/1
  # DELETE /congregacions/1.json
  def destroy
    @congregacion = Congregacion.find(params[:id])
    @congregacion.destroy

    respond_to do |format|
      format.html { redirect_to congregacions_url }
      format.json { head :ok }
    end
  end
  
  def vermapa
    @mapa = Congregacion.all 
    @grupos= GrupoBiblico.all
    @unidades= Unidadevangelismo.all
  end
end

app/controllers/grupo_biblicos_controller.rb
class GrupoBiblicosController < ApplicationController
  # GET /grupo_biblicos
  # GET /grupo_biblicos.json
  def index
    @grupo_biblicos = GrupoBiblico.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grupo_biblicos }
    end
  end

  # GET /grupo_biblicos/1
  # GET /grupo_biblicos/1.json
  def show
    @grupo_biblico = GrupoBiblico.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grupo_biblico }
    end
  end

  # GET /grupo_biblicos/new
  # GET /grupo_biblicos/new.json
  def new
    @grupo_biblico = GrupoBiblico.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grupo_biblico }
    end
  end

  # GET /grupo_biblicos/1/edit
  def edit
    @grupo_biblico = GrupoBiblico.find(params[:id])
  end

  # POST /grupo_biblicos
  # POST /grupo_biblicos.json
  def create
    @grupo_biblico = GrupoBiblico.new(params[:grupo_biblico])

    respond_to do |format|
      if @grupo_biblico.save
        format.html { redirect_to @grupo_biblico, notice: 'Grupo biblico was successfully created.' }
        format.json { render json: @grupo_biblico, status: :created, location: @grupo_biblico }
      else
        format.html { render action: "new" }
        format.json { render json: @grupo_biblico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grupo_biblicos/1
  # PUT /grupo_biblicos/1.json
  def update
    @grupo_biblico = GrupoBiblico.find(params[:id])

    respond_to do |format|
      if @grupo_biblico.update_attributes(params[:grupo_biblico])
        format.html { redirect_to @grupo_biblico, notice: 'Grupo biblico was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @grupo_biblico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupo_biblicos/1
  # DELETE /grupo_biblicos/1.json
  def destroy
    @grupo_biblico = GrupoBiblico.find(params[:id])
    @grupo_biblico.destroy

    respond_to do |format|
      format.html { redirect_to grupo_biblicos_url }
      format.json { head :ok }
    end
  end
end

app/controllers/unidadevangelismos_controller.rb
class UnidadevangelismosController < ApplicationController
  # GET /unidadevangelismos
  # GET /unidadevangelismos.json
  def index
    @unidadevangelismos = Unidadevangelismo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unidadevangelismos }
    end
  end

  # GET /unidadevangelismos/1
  # GET /unidadevangelismos/1.json
  def show
    @unidadevangelismo = Unidadevangelismo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unidadevangelismo }
    end
  end

  # GET /unidadevangelismos/new
  # GET /unidadevangelismos/new.json
  def new
    @unidadevangelismo = Unidadevangelismo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unidadevangelismo }
    end
  end

  # GET /unidadevangelismos/1/edit
  def edit
    @unidadevangelismo = Unidadevangelismo.find(params[:id])
  end

  # POST /unidadevangelismos
  # POST /unidadevangelismos.json
  def create
    @unidadevangelismo = Unidadevangelismo.new(params[:unidadevangelismo])

    respond_to do |format|
      if @unidadevangelismo.save
        format.html { redirect_to @unidadevangelismo, notice: 'Unidadevangelismo was successfully created.' }
        format.json { render json: @unidadevangelismo, status: :created, location: @unidadevangelismo }
      else
        format.html { render action: "new" }
        format.json { render json: @unidadevangelismo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unidadevangelismos/1
  # PUT /unidadevangelismos/1.json
  def update
    @unidadevangelismo = Unidadevangelismo.find(params[:id])

    respond_to do |format|
      if @unidadevangelismo.update_attributes(params[:unidadevangelismo])
        format.html { redirect_to @unidadevangelismo, notice: 'Unidadevangelismo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @unidadevangelismo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidadevangelismos/1
  # DELETE /unidadevangelismos/1.json
  def destroy
    @unidadevangelismo = Unidadevangelismo.find(params[:id])
    @unidadevangelismo.destroy

    respond_to do |format|
      format.html { redirect_to unidadevangelismos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/congregacions_helper.rb
module CongregacionsHelper
end

app/helpers/grupo_biblicos_helper.rb
module GrupoBiblicosHelper
end

app/helpers/unidadevangelismos_helper.rb
module UnidadevangelismosHelper
end

app/views/congregacions/_form.html.erb
<%= form_for(@congregacion) do |f| %>
  <% if @congregacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@congregacion.errors.count, "error") %> prohibited this congregacion from being saved:</h2>

      <ul>
      <% @congregacion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Teléfono %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :Dirección %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :Email %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :Latitud %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :Longitud %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/congregacions/edit.html.erb
<h1>Editing congregacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @congregacion %> |
<%= link_to 'Back', congregacions_path %>

app/views/congregacions/index.html.erb
<h1>Listado de Congregaciones</h1>
<div id="MainWrapper">
<table>
  <tr>
    <th>Nombre</th>
    <th>Teléfono</th>
    <th>Dirección</th>
    <th>Email</th>
    <th>Latitud</th>
    <th>Longitud</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @congregacions.each do |congregacion| %>
  <tr>
    <td><%= congregacion.name %></td>
    <td><%= congregacion.phone %></td>
    <td><%= congregacion.address %></td>
    <td><%= congregacion.mail %></td>
    <td><%= congregacion.lat %></td>
    <td><%= congregacion.lon %></td>
    <td id="ver"><%= link_to 'Ver', congregacion %></td>
    <td id="editar"><%= link_to 'Editar', edit_congregacion_path(congregacion) %></td>
    <td id="eliminar"><%= link_to 'Eliminar', congregacion, confirm: 'Está seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>

</div>
<br />

app/views/congregacions/new.html.erb
<h1>Nueva congregaci&oacute;n</h1>

<%= render 'form' %>

<%= link_to 'Back', congregacions_path %>

app/views/congregacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @congregacion.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @congregacion.phone %>
</p>

<p>
  <b>Address:</b>
  <%= @congregacion.address %>
</p>

<p>
  <b>Mail:</b>
  <%= @congregacion.mail %>
</p>

<p>
  <b>Lat:</b>
  <%= @congregacion.lat %>
</p>

<p>
  <b>Lon:</b>
  <%= @congregacion.lon %>
</p>


<%= link_to 'Edit', edit_congregacion_path(@congregacion) %> |
<%= link_to 'Back', congregacions_path %>

app/views/congregacions/vermapa.html.erb
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/src/infobox.js"></script>
<script type="text/javascript">
 var totalcon=0;
 var totalue=0;
 var totalgp=0;
 var type=[];
    function init() {
        var secheltLoc = new google.maps.LatLng(7.903043430148051, -72.49341487884521),
            markers;

        var myMapOptions = {
             zoom: 13,
             center: secheltLoc,
             mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var theMap = new google.maps.Map(document.getElementById("map_canvas"), myMapOptions);
        // var limits = new google.maps.LatLngBounds();
        
            function initMarkers(theMap, markerData) {
            var newMarkers = [],
                marker;

            var iconRed='http://javiermedrano.net/images/pines/pinccon.png'
            var iconBlue='http://javiermedrano.net/images/pines/pinccgp.png'
            var iconGreen='http://javiermedrano.net/images/pines/pinccue.png'
            var iconType=[];
            
            iconType["0"] = iconRed;
            iconType["1"] = iconGreen;
            iconType["2"] = iconBlue;
           
            var image;
            // ciclo que recoge los registros de >>>>>>>>>>>>>> Congregaciones  >>>>>>
            for(var i=0; i<markerData.length; i++) {
              
                switch (type[i]) {
                    
                    case "1":
                        image=iconType["0"];
                        marker = new google.maps.Marker({
                            map: theMap,
                            draggable: true,
                            position: markerData[i].latLng,
                            visible: true,
                            icon:image,
                            animation: google.maps.Animation.DROP
                            })
     
                        // alert (type[i]);
                        
                        break; 
                     
                     case "2":
                        image=iconType["1"];
                        marker = new google.maps.Marker({
                            map: theMap,
                            draggable: true,
                            position: markerData[i].latLng,
                            visible: true,
                            icon:image,
                            animation: google.maps.Animation.DROP
                            })
     
                        // alert (type[i]);
                        
                        break; 
                    
                        case "3":
                        image=iconType["2"];
                        marker = new google.maps.Marker({
                            map: theMap,
                            draggable: true,
                            position: markerData[i].latLng,
                            visible: true,
                            icon:image,
                            animation: google.maps.Animation.DROP
                            })
     
                        // alert (type[i]);
                        
                        break; 

                        default:
                        image=iconType["0"];
                        marker = new google.maps.Marker({
                            map: theMap,
                            draggable: true,
                            position: markerData[i].latLng,
                            visible: true,
                            icon:image,
                            animation: google.maps.Animation.DROP
                            })

                }
                
                newMarkers.push(marker); 
                
                // marker = new google.maps.Marker({
                //     map: theMap,
                //     draggable: true,
                //     position: markerData[i].latLng,
                //     visible: true,
                //     icon:image,
                //     animation: google.maps.Animation.DROP
                //     })
                
                    
                //     newMarkers.push(marker); 
                   
                

                //define the text and style for all infoboxes
                var boxText = document.createElement("div");
                boxText.style.cssText = "border: 1px solid black; margin-top: 8px; background:#333; color:#FFF; font-family:Arial; font-size:12px; padding: 5px; border-radius:6px; -webkit-border-radius:6px; -moz-border-radius:6px;";
                boxText.innerHTML = "<h3>"+markerData[i].name +"</h3>"+ markerData[i].direccion + "<br>" + markerData[i].telefono+ "<br>" + markerData[i].email;

                //define the options for all infoboxes
                var myOptions = {
                     content: boxText,
                     disableAutoPan: false,
                     maxWidth: 0,
                     pixelOffset: new google.maps.Size(-140, 0),
                     zIndex: null,
                     boxStyle: { 
                        background: "url('http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/examples/tipbox.gif') no-repeat",
                        opacity: 0.85,
                        width: "250px"
                    },
                    closeBoxMargin: "12px 4px 2px 2px",
                    closeBoxURL: "http://www.google.com/intl/en_us/mapfiles/close.gif",
                    infoBoxClearance: new google.maps.Size(1, 1),
                    isHidden: false,
                    pane: "floatPane",
                    enableEventPropagation: true};
                    

                //Define the infobox
                newMarkers[i].infobox = new InfoBox(myOptions);
                

                //Open infobox for marker when user clicks on it.  This code pattern, with the callback returning a function, is needed to
                //create closure.  This pattern is often needed when using callbacks inside a for-loop.  If you used a normal callback (in 
                //which there is no inner function), there would be no closure and all markers would open the infobox of the last marker
                //created in the for-loop
                google.maps.event.addListener(marker, 'click', (function(marker, i) {
                return function() {
                    for ( h = 0; h < newMarkers.length; h++ ) {
                        newMarkers[h].infobox.close();
                    }
                    newMarkers[i].infobox.open(theMap, this);
                    theMap.panTo(markerData[i].latLng);
                    }
                })(marker, i));
                
            }
            

            // ciclo que recoge los registros de >>>>>>>>>>>>>> Unidades de Evangelismo  >>>>>>




            return newMarkers
            
        }
       
       var markerData=[];
       <% contador = 0 %>
       <%total=0%>
        <% @mapa.each do |con| %>
        <%= contador += 1 %>
       
         markerData.push({latLng: new google.maps.LatLng(<%= con.lat%>, <%= con.lon %>), name: "<%= con.name %>", direccion: "<%= con.address %>", telefono: "<%= con.phone %>", email:"<%= con.mail %>"})  <%= "," if @mapa.count != contador %>  

            type.push("1");
            
        <% end %>;
        totalcon=totalcon+markerData.length;

        <% contador2 = 0 %>
        <% @unidades.each do |con2| %>
        <%= contador2 += 1 %>
        <%= total += 1 %>
         markerData.push({latLng: new google.maps.LatLng(<%= con2.lat%>, <%= con2.lon %>), name: "<%= con2.name %>", direccion: "<%= con2.address %>", telefono: "<%= con2.phone %>", email:"<%= con2.mail %>"})  <%= "," if @unidades.count != contador2 %>           
            type.push("2");
        <% end %>;
        totalue=totalue+markerData.length;


        <% contador3 = 0 %>
        <% @grupos.each do |con3| %>
        <%= contador3 += 1 %>
        <%= total += 1 %>
         markerData.push({latLng: new google.maps.LatLng(<%= con3.lat%>, <%= con3.lon %>), name: "<%= con3.name %>", direccion: "<%= con3.address %>", telefono: "<%= con3.phone %>", email:"<%= con3.mail %>"})  <%= "," if @grupos.count != contador3 %>           
         type.push("3");
        <% end %>
       totalgp=totalgp+markerData.length;
       markers = initMarkers(theMap,markerData);

    
        
      
    }
</script>

<title>Ubicaciones</title>
</head>
<body onload="init()">
    <div id="map_canvas" style="width: 900px; height: 600px; margin: auto;"></div>
    
<!--     <input type="button" onclick="init()" value="ver mapa"/> --> -->
    <br />
    <%= link_to 'Back', congregacions_path %>
    <br />
    </div>
    
</body>

</html>

app/views/grupo_biblicos/_form.html.erb
<%= form_for(@grupo_biblico) do |f| %>
  <% if @grupo_biblico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grupo_biblico.errors.count, "error") %> prohibited this grupo_biblico from being saved:</h2>

      <ul>
      <% @grupo_biblico.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grupo_biblicos/edit.html.erb
<h1>Editing grupo_biblico</h1>

<%= render 'form' %>

<%= link_to 'Show', @grupo_biblico %> |
<%= link_to 'Back', grupo_biblicos_path %>

app/views/grupo_biblicos/index.html.erb
<h1>Listing grupo_biblicos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Mail</th>
    <th>Lat</th>
    <th>Lon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @grupo_biblicos.each do |grupo_biblico| %>
  <tr>
    <td><%= grupo_biblico.name %></td>
    <td><%= grupo_biblico.phone %></td>
    <td><%= grupo_biblico.address %></td>
    <td><%= grupo_biblico.mail %></td>
    <td><%= grupo_biblico.lat %></td>
    <td><%= grupo_biblico.lon %></td>
    <td><%= link_to 'Show', grupo_biblico %></td>
    <td><%= link_to 'Edit', edit_grupo_biblico_path(grupo_biblico) %></td>
    <td><%= link_to 'Destroy', grupo_biblico, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grupo biblico', new_grupo_biblico_path %>

app/views/grupo_biblicos/new.html.erb
<h1>New grupo_biblico</h1>

<%= render 'form' %>

<%= link_to 'Back', grupo_biblicos_path %>

app/views/grupo_biblicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @grupo_biblico.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @grupo_biblico.phone %>
</p>

<p>
  <b>Address:</b>
  <%= @grupo_biblico.address %>
</p>

<p>
  <b>Mail:</b>
  <%= @grupo_biblico.mail %>
</p>

<p>
  <b>Lat:</b>
  <%= @grupo_biblico.lat %>
</p>

<p>
  <b>Lon:</b>
  <%= @grupo_biblico.lon %>
</p>


<%= link_to 'Edit', edit_grupo_biblico_path(@grupo_biblico) %> |
<%= link_to 'Back', grupo_biblicos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Map</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


<%= link_to 'Congregaciónes', congregacions_path %> | <%= link_to 'Unidades de Evangelismo', unidadevangelismos_path %> | <%= link_to 'Grupos Bíblicos', grupo_biblicos_path%> | 
<%= link_to 'Ver mapa', :controller => "congregacions", :action => "vermapa"%>
</body>
</html>

app/views/unidadevangelismos/_form.html.erb
<%= form_for(@unidadevangelismo) do |f| %>
  <% if @unidadevangelismo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unidadevangelismo.errors.count, "error") %> prohibited this unidadevangelismo from being saved:</h2>

      <ul>
      <% @unidadevangelismo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unidadevangelismos/edit.html.erb
<h1>Editing unidadevangelismo</h1>

<%= render 'form' %>

<%= link_to 'Show', @unidadevangelismo %> |
<%= link_to 'Back', unidadevangelismos_path %>

app/views/unidadevangelismos/index.html.erb
<h1>Listing unidadevangelismos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Mail</th>
    <th>Lat</th>
    <th>Lon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @unidadevangelismos.each do |unidadevangelismo| %>
  <tr>
    <td><%= unidadevangelismo.name %></td>
    <td><%= unidadevangelismo.phone %></td>
    <td><%= unidadevangelismo.address %></td>
    <td><%= unidadevangelismo.mail %></td>
    <td><%= unidadevangelismo.lat %></td>
    <td><%= unidadevangelismo.lon %></td>
    <td><%= link_to 'Show', unidadevangelismo %></td>
    <td><%= link_to 'Edit', edit_unidadevangelismo_path(unidadevangelismo) %></td>
    <td><%= link_to 'Destroy', unidadevangelismo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unidadevangelismo', new_unidadevangelismo_path %>

app/views/unidadevangelismos/new.html.erb
<h1>New unidadevangelismo</h1>

<%= render 'form' %>

<%= link_to 'Back', unidadevangelismos_path %>

app/views/unidadevangelismos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @unidadevangelismo.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @unidadevangelismo.phone %>
</p>

<p>
  <b>Address:</b>
  <%= @unidadevangelismo.address %>
</p>

<p>
  <b>Mail:</b>
  <%= @unidadevangelismo.mail %>
</p>

<p>
  <b>Lat:</b>
  <%= @unidadevangelismo.lat %>
</p>

<p>
  <b>Lon:</b>
  <%= @unidadevangelismo.lon %>
</p>


<%= link_to 'Edit', edit_unidadevangelismo_path(@unidadevangelismo) %> |
<%= link_to 'Back', unidadevangelismos_path %>